Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -60,9 +60,15 @@ jobs:
           TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
         run: |
           CAPTION=$(cat app_info.txt)
-          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
+          RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
             -F chat_id="${TELEGRAM_CHAT_ID}" \
             -F document=@"build/app/outputs/flutter-apk/app-arm64-v8a-release.apk" \
-            -F caption="${CAPTION}" \
-            -F parse_mode="Markdown"
-            
+            -F caption="${CAPTION}")
+          
+          echo "Telegram API Response: $RESPONSE"
+          
+          if [[ "$RESPONSE" != *"\"ok\":true"* ]]; then
+            echo "Error sending document to Telegram!"
+            exit 1
+          fi
+          
